from datetime import datetime
from typing import List, Optional, Dict, Any
from pydantic import BaseModel
import uuid
from .core import AlertSeverity, TrendType

class TrendAnalysis(BaseModel):
    """Analysis of a detected trend in system metrics."""
    metric_name: str
    current_value: float
    trend_direction: str  # "increasing", "decreasing", "stable"
    time_window_minutes: int

class ProactiveAlert(BaseModel):
    """Alert generated by proactive monitoring."""
    alert_id: str = str(uuid.uuid4())
    detected_at: datetime = datetime.now()
    trend_type: TrendType
    severity: AlertSeverity
    affected_services: List[str]
    description: str
    trend_data: TrendAnalysis
    recommended_actions: List[str] = []