from datetime import datetime
from typing import List, Optional, Dict, Any
from pydantic import BaseModel
import uuid
# Kiro correctly moved these enums to core.py, so this import is correct.
from .core import AlertSeverity, TrendType

class TrendAnalysis(BaseModel):
    """Analysis of a detected trend in system metrics."""
    metric_name: str
    current_value: float
    baseline_value: float
    trend_direction: str  # "increasing", "decreasing", "stable"
    confidence: float
    time_window_minutes: int  # This is the field that was missing
    data_points: List[Dict[str, Any]]

class ProactiveAlert(BaseModel):
    """Alert generated by proactive monitoring."""
    alert_id: str = str(uuid.uuid4())
    detected_at: datetime = datetime.now()
    trend_type: TrendType
    severity: AlertSeverity
    affected_services: List[str]
    description: str  # This field was also missing
    trend_data: TrendAnalysis
    recommended_actions: List[str] = []
    resolved_at: Optional[datetime] = None