"""
Jira Integration Stub — creates incident tickets in Jira automatically.

In production, this would use the Jira REST API (via atlassian-python-api or httpx).
For now it provides the interface, builds the payload, and logs it.
"""

import json
from datetime import datetime
from typing import Dict, Any, Optional, List

from ..core import logger


class JiraClient:
    """Creates and manages Jira incident tickets."""

    def __init__(self, base_url: Optional[str] = None, project_key: str = "INC",
                 email: Optional[str] = None, api_token: Optional[str] = None):
        self.base_url = base_url
        self.project_key = project_key
        self.email = email
        self.api_token = api_token
        self._connected = bool(base_url and email and api_token)
        logger.info("JiraClient initialised", project=project_key, live=self._connected)

    # ─── Public API ──────────────────────────────

    def create_incident_ticket(
        self,
        summary: str,
        description: str,
        severity: str = "High",
        affected_services: List[str] = None,
        remediation_steps: List[str] = None,
        labels: List[str] = None,
    ) -> Dict[str, Any]:
        """Create a Jira issue for an incident."""

        priority_map = {"low": "Low", "medium": "Medium", "high": "High", "critical": "Highest"}
        priority = priority_map.get(severity.lower(), "High")

        body = self._format_description(description, affected_services or [],
                                         remediation_steps or [])

        payload = {
            "fields": {
                "project": {"key": self.project_key},
                "issuetype": {"name": "Bug"},
                "summary": f"[Clarity] {summary}",
                "description": body,
                "priority": {"name": priority},
                "labels": labels or ["clarity-ai", "auto-generated", "incident"],
            }
        }

        return self._dispatch(payload)

    def update_ticket(self, ticket_key: str, comment: str) -> Dict[str, Any]:
        """Add a follow-up comment to an existing ticket."""
        payload = {
            "ticket_key": ticket_key,
            "comment": {
                "body": f"🤖 *Clarity AI Update*\n\n{comment}\n\n_Updated at {datetime.now().isoformat()}_"
            }
        }
        return self._dispatch(payload, action="comment")

    # ─── Internals ───────────────────────────────

    def _priority_from_confidence(self, confidence_score: float) -> str:
        """Map AI confidence score to Jira priority tier.

        Mapping (Requirement 8.7):
          >= 0.85 → Highest
          >= 0.70 → High
          >= 0.50 → Medium
          <  0.50 → Low
        """
        if confidence_score >= 0.85:
            return "Highest"
        elif confidence_score >= 0.70:
            return "High"
        elif confidence_score >= 0.50:
            return "Medium"
        else:
            return "Low"

    def _format_description(self, description, services, steps):
        services_list = [f"* {s}" for s in services] if services else ["* N/A"]
        steps_list = [f"# {s}" for s in steps] if steps else ["# No automated remediation available"]

        parts = [
            "h3. 🤖 AI-Generated Incident Report",
            "",
            description,
            "",
            "h4. Affected Services",
            *services_list,
            "",
            "h4. Remediation Steps",
            *steps_list,
            "",
            "----",
            f"_Auto-generated by Clarity AI at {datetime.now().isoformat()}_",
        ]
        return "\n".join(parts)

    def _dispatch(self, payload: Dict[str, Any], action: str = "create") -> Dict[str, Any]:
        """
        In production: POST/PUT to Jira REST API.
        Stub mode: log and return mock response.
        """
        if self._connected:
            # Production path — would do:
            #   import httpx
            #   headers = {"Accept": "application/json", "Content-Type": "application/json"}
            #   auth = (self.email, self.api_token)
            #   url = f"{self.base_url}/rest/api/3/issue"
            #   resp = httpx.post(url, json=payload, auth=auth, headers=headers)
            #   return resp.json()
            logger.info(f"Jira {action} dispatched (stub)", url=self.base_url)
        else:
            logger.info(f"Jira {action} (dry-run)", payload_fields=list(payload.get("fields", {}).keys()))

        mock_key = f"{self.project_key}-{int(datetime.now().timestamp()) % 10000}"
        return {
            "ok": True,
            "mode": "stub",
            "key": mock_key,
            "payload": payload,
        }
