"""
Report Exporter — generates professional incident reports in Markdown and JSON.
"""

import json
from datetime import datetime
from typing import Dict, Any, List, Optional
import re

from ..core import logger


class ReportExporter:
    """Generates and exports professional incident reports."""

    def __init__(self):
        self.generated_at = datetime.now()

    # ─── Markdown Export ─────────────────────────

    def to_markdown(
        self,
        analysis_result: str,
        timeline_data: List[Dict[str, Any]],
        remediation_cmd: str = "",
        conversation_history: List[Dict[str, str]] = None,
        incident_id: str = "",
    ) -> str:
        """Generate a full professional Markdown incident report."""
        parsed = self._parse_analysis(analysis_result)
        ts = self.generated_at.strftime("%Y-%m-%d %H:%M:%S UTC")

        sections = [
            f"# 🤖 Clarity Incident Report",
            f"",
            f"**Incident ID:** {incident_id or parsed.get('incident_id', 'N/A')}",
            f"**Generated:** {ts}",
            f"**AI Confidence:** {parsed.get('confidence_score', 0.0):.1%}",
            f"",
            f"---",
            f"",
            f"## Executive Summary",
            f"",
            parsed.get("summary", "No summary available."),
            f"",
            f"## Root Cause Analysis",
            f"",
            parsed.get("root_cause_description", "Root cause could not be determined."),
            f"",
            f"## Affected Components",
            f"",
        ]

        for comp in parsed.get("affected_components", ["Unknown"]):
            sections.append(f"- {comp}")

        sections.extend([
            f"",
            f"## Incident Timeline",
            f"",
            f"| Time | Level | Service | Message |",
            f"|------|-------|---------|---------|",
        ])

        if timeline_data and len(timeline_data) > 25:
            logger.warning(
                "Timeline truncated for Markdown report",
                original_count=len(timeline_data),
                truncated_to=25,
            )

        for event in (timeline_data or [])[:25]:
            time = event.get("timestamp", "?")
            level = event.get("level", "INFO")
            svc = event.get("service", "—")
            msg = str(event.get("message", ""))[:80].replace("|", "\\|")
            sections.append(f"| {time} | {level} | {svc} | {msg} |")

        sections.extend([
            f"",
            f"## Remediation",
            f"",
        ])

        if remediation_cmd:
            sections.extend([
                f"**Recommended Command:**",
                f"```bash",
                remediation_cmd,
                f"```",
            ])

        steps = parsed.get("remediation_steps", [])
        if steps:
            sections.append(f"")
            sections.append(f"**Step-by-Step:**")
            for i, step in enumerate(steps, 1):
                sections.append(f"{i}. {step}")

        # Co-Pilot Q&A section
        if conversation_history:
            sections.extend([
                f"",
                f"## Co-Pilot Investigation Log",
                f"",
            ])
            for qa in conversation_history:
                sections.append(f"**Q:** {qa.get('question', '')}")
                sections.append(f"")
                sections.append(f"> {qa.get('answer', '')[:300]}")
                sections.append(f"")

        sections.extend([
            f"",
            f"---",
            f"",
            f"*Report generated by [Clarity AI](https://github.com/your-org/clarity) — AI DevOps Copilot*",
        ])

        return "\n".join(sections)

    # ─── JSON Export ─────────────────────────────

    def to_json(
        self,
        analysis_result: str,
        timeline_data: List[Dict[str, Any]],
        remediation_cmd: str = "",
        conversation_history: List[Dict[str, str]] = None,
        incident_id: str = "",
    ) -> str:
        """Generate a structured JSON incident report."""
        parsed = self._parse_analysis(analysis_result)

        report = {
            "report_version": "1.0",
            "generated_at": self.generated_at.isoformat(),
            "incident_id": incident_id or parsed.get("incident_id", ""),
            "summary": parsed.get("summary", ""),
            "root_cause": {
                "description": parsed.get("root_cause_description", ""),
                "confidence_score": parsed.get("confidence_score", 0.0),
            },
            "affected_components": parsed.get("affected_components", []),
            "remediation": {
                "command": remediation_cmd,
                "steps": parsed.get("remediation_steps", []),
            },
            "timeline": self._build_json_timeline(timeline_data),
            "investigation": [
                {
                    "question": qa.get("question", ""),
                    "answer": qa.get("answer", ""),
                    "timestamp": qa.get("timestamp", ""),
                }
                for qa in (conversation_history or [])
            ],
        }

        return json.dumps(report, indent=2, default=str)

    # ─── Save to file ────────────────────────────

    def save(self, content: str, filepath: str) -> str:
        """Write report content to a file."""
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        logger.info("Report saved", path=filepath, size=len(content))
        return filepath

    # ─── Internals ───────────────────────────────

    def _build_json_timeline(self, timeline_data: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Return at most 50 timeline events, logging a warning if truncation occurs."""
        if timeline_data and len(timeline_data) > 50:
            logger.warning(
                "Timeline truncated for JSON report",
                original_count=len(timeline_data),
                truncated_to=50,
            )
        return [
            {
                "timestamp": e.get("timestamp", ""),
                "level": e.get("level", "INFO"),
                "service": e.get("service", ""),
                "message": e.get("message", ""),
            }
            for e in (timeline_data or [])[:50]
        ]

    def _parse_analysis(self, analysis_result: str) -> Dict[str, Any]:
        """Extract structured data from the analysis result string."""
        try:
            match = re.search(r'\{.*\}', analysis_result, re.DOTALL)
            if match:
                return json.loads(match.group(0))
            return json.loads(analysis_result)
        except Exception:
            return {"summary": analysis_result[:500], "raw": True}
