"""
Slack Integration Stub — sends incident alerts and reports to Slack channels.

In production, this would use the Slack Web API (slack_sdk).
For now it provides the interface and logs the payload so the
integration can be wired up later with real credentials.
"""

import json
from datetime import datetime
from typing import Dict, Any, Optional, List

from ..core import logger


class SlackNotifier:
    """Sends incident notifications to a Slack channel."""

    def __init__(self, webhook_url: Optional[str] = None, channel: str = "#incidents"):
        self.webhook_url = webhook_url
        self.channel = channel
        logger.info("SlackNotifier initialised", channel=channel, live=bool(webhook_url))

    # ─── Public API ──────────────────────────────

    def send_alert(self, title: str, severity: str, description: str,
                   affected_services: List[str] = None, actions: List[str] = None) -> Dict[str, Any]:
        """Send a proactive alert to Slack."""
        payload = self._build_alert_payload(title, severity, description,
                                            affected_services or [], actions or [])
        return self._dispatch(payload)

    def send_incident_report(self, report_markdown: str, incident_id: str = "") -> Dict[str, Any]:
        """Post a full incident report."""
        payload = {
            "channel": self.channel,
            "blocks": [
                {
                    "type": "header",
                    "text": {"type": "plain_text", "text": f"🤖 Clarity Incident Report {incident_id}"}
                },
                {
                    "type": "section",
                    "text": {"type": "mrkdwn", "text": report_markdown[:3000]}
                },
                {
                    "type": "context",
                    "elements": [
                        {"type": "mrkdwn", "text": f"Generated by Clarity AI at {datetime.now().isoformat()}"}
                    ]
                }
            ]
        }
        return self._dispatch(payload)

    # ─── Internals ───────────────────────────────

    def _build_alert_payload(self, title, severity, description, services, actions):
        color_map = {"low": "#36a64f", "medium": "#daa520", "high": "#ff6347", "critical": "#dc143c"}
        color = color_map.get(severity.lower(), "#808080")

        attachment = {
            "color": color,
            "blocks": [
                {"type": "header", "text": {"type": "plain_text", "text": f"⚠️ {title}"}},
                {"type": "section", "fields": [
                    {"type": "mrkdwn", "text": f"*Severity:*\n{severity.upper()}"},
                    {"type": "mrkdwn", "text": f"*Services:*\n{', '.join(services) or 'N/A'}"},
                ]},
                {"type": "section", "text": {"type": "mrkdwn", "text": description}},
            ]
        }
        if actions:
            attachment["blocks"].append({
                "type": "section",
                "text": {"type": "mrkdwn", "text": "*Recommended Actions:*\n" + "\n".join(f"• {a}" for a in actions)}
            })

        return {"channel": self.channel, "attachments": [attachment]}

    def _dispatch(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """
        In production: POST to webhook_url via httpx/requests.
        Stub mode: log and return the payload.
        """
        if self.webhook_url:
            # Production path — would do:
            #   import httpx
            #   resp = httpx.post(self.webhook_url, json=payload)
            #   return {"ok": resp.status_code == 200, "status": resp.status_code}
            logger.info("Slack webhook dispatched (stub)", url=self.webhook_url)
        else:
            logger.info("Slack dispatch (dry-run)", payload_keys=list(payload.keys()))

        return {"ok": True, "mode": "stub", "payload": payload}
